version: "3.3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - "./adguardhome/work:/opt/adguardhome/work"
      - "./adguardhome/conf:/opt/adguardhome/conf"
    ports:
      - "53:53/tcp" # Plain DNS
      - "53:53/udp" # Plain DNS
      - "80:80/tcp" # Admin panel and HTTPS/DNS-over-HTTPS server
      - "443:443/tcp" # Admin panel and HTTPS/DNS-over-HTTPS server
      - "443:443/udp" # Admin panel and HTTPS/DNS-over-HTTPS server
      - "3000:3000/tcp" # Admin panel and HTTPS/DNS-over-HTTPS server
      #- "853:853/tcp" # DNS-over-TLS
      #- "5443:5443/tcp" # DNSCrypt
      #- "5443:5443/upd" # DNSCrypt
